apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "chart.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "chart.fullname" . }}
  secretName: {{ include "chart.fullname" . }}-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  usages:
  - server auth
  - digital signature
  - key encipherment
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selfSigned: {}
