# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager 0.11 check https://docs.cert-manager.io/en/latest/tasks/upgrading/index.html for breaking changes

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
  namespace: kube-system
spec:
  dnsNames:
  - webhook-server.kube-system.svc
  - webhook-server.kube-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: pod-mutator-ca
  secretName: webhook-server-cert
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  usages:
  - server auth
  - digital signature
  - key encipherment
