apiVersion: kustomize.config.k8s.io/v1beta1
kind: Configuration

nameReference:
- kind: Certificate
  group: cert-manager.io
  fieldSpecs:
  - kind: MutatingWebhookConfiguration
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/caBundle

varReference:
- kind: Certificate
  group: cert-manager.io
  path: spec/commonName
- kind: Certificate
  group: cert-manager.io
  path: spec/dnsNames
